package generational_cache

import (
	"encoding/binary"
	"github.com/ethereum/go-ethereum/common"
)

type LocalNodeCacheKey interface {
	ToCacheKey() [24]byte
	comparable
}

type Uint64LocalCacheKey struct {
	key uint64
}

func (ukey Uint64LocalCacheKey) ToCacheKey() [24]byte {
	ret := [24]byte{}
	copy(ret[:], binary.LittleEndian.AppendUint64([]byte{}, ukey.key))
	return ret
}

type AddressLocalCacheKey struct {
	address common.Address
}

func (key AddressLocalCacheKey) ToCacheKey() [24]byte {
	// addresses are generated by hashing, so no need to hash again
	// we fill the last four bytes with duplicates of the first four, which might be useful
	ret := [24]byte{}
	copy(ret[0:20], key.address.Bytes())
	copy(ret[20:24], ret[0:4])
	return ret
}
